# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0002_auto_20170302_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pub_date',
            field=models.CharField(default=2008, max_length=320),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='foodcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.FoodCategory'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.Menu'),
        ),
        migrations.AlterField(
            model_name='food',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.Order'),
        ),
    ]
