# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0004_auto_20170307_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='day',
        ),
        migrations.RemoveField(
            model_name='food',
            name='month',
        ),
        migrations.RemoveField(
            model_name='food',
            name='year',
        ),
        migrations.AddField(
            model_name='food',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
