# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0004_cart_foodorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorder',
            old_name='book',
            new_name='food',
        ),
    ]
