# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0005_auto_20170307_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'foods'},
        ),
    ]
