# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0006_auto_20170308_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pub_date_string',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
