# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0007_food_pub_date_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='pub_date_string',
        ),
    ]
