# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0008_auto_20170508_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
