# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0009_auto_20170611_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menucategory',
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
