# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0010_auto_20171122_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ultimatefitbackend.Food')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('stock', models.IntegerField(default=0)),
            ],
            bases=('ultimatefitbackend.food',),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_item',
            field=models.ManyToManyField(blank=True, to='ultimatefitbackend.FoodItem'),
        ),
    ]
