# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0010_auto_20171121_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.Food')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.Menu')),
            ],
        ),
    ]
