# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0011_auto_20171122_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='date',
            new_name='pub_date',
        ),
    ]
