# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0011_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ManyToManyField(to='ultimatefitbackend.Food'),
        ),
    ]
