# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0012_menu_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food',
            field=models.ManyToManyField(blank=True, to='ultimatefitbackend.Food'),
        ),
    ]
