# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0012_auto_20171122_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='food_ptr',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='food_item',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
