# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0013_auto_20171121_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
