# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0014_auto_20171121_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
