# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0014_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='food_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.FoodItem'),
        ),
    ]
