# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0015_auto_20171122_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food_item',
        ),
    ]
