# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0017_auto_20171122_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.Food')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.Menu')),
            ],
        ),
    ]
