# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0018_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
