# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0019_food_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='menu',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
