# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0020_auto_20171123_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.Menu'),
        ),
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
