# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0022_auto_20171123_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='description',
        ),
    ]
