# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0024_auto_20171124_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'get_latest_by': 'pub_date', 'verbose_name_plural': 'foods'},
        ),
    ]
