# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0025_auto_20171124_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'foods'},
        ),
    ]
