# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0026_auto_20171124_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='pub_date',
        ),
    ]
