# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0027_remove_food_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['menu'], 'verbose_name_plural': 'foods'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['pub_date']},
        ),
    ]
