# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0028_auto_20171124_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_type',
            field=models.ManyToManyField(blank=True, through='ultimatefitbackend.Food', to='ultimatefitbackend.FoodType'),
        ),
    ]
