# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0029_menu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(max_length=320, unique=True),
        ),
    ]
