# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0030_auto_20171127_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='available_categories',
            field=models.CharField(choices=[('LE', 'Lean On Me'), ('MA', 'Maintain'), ('HE', 'Heavy Duty')], default='MA', max_length=2),
        ),
    ]
