# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 15:37
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0031_foodtype_available_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='available_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LE', 'Lean On Me'), ('MA', 'Maintain'), ('HE', 'Heavy Duty')], max_length=8),
        ),
    ]
