# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 02:54
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0034_auto_20171224_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LE', 'Lean On Me'), ('MA', 'Maintain'), ('HE', 'Heavy Duty')], max_length=8),
        ),
    ]
