# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0035_auto_20171224_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, choices=[('LE', 'Lean On Me'), ('MA', 'Maintain'), ('HE', 'Heavy Duty')], max_length=100),
        ),
    ]
