# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0036_auto_20171224_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='cal_heavy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='cal_lean',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='cal_maintain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='carb_heavy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='carb_lean',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='carb_maintain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='fat_heavy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='fat_lean',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='fat_maintain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='protein_heavy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='protein_lean',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='protein_maintain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
