# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0037_auto_20180116_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, choices=[('LEAN', 'Lean On Me'), ('MAINTAIN', 'Maintain'), ('HEAVY', 'Heavy Duty')], max_length=100),
        ),
    ]
