# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 15:38
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0038_auto_20180116_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='available_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LEAN', 'Lean On Me'), ('MAINTAIN', 'Maintain'), ('HEAVY', 'Heavy Duty')], max_length=19),
        ),
    ]
