# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0039_auto_20180116_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(help_text='This is the help text', max_length=320, unique=True),
        ),
    ]
