# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0040_auto_20180205_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='name_vn',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
