# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0041_foodtype_name_vn'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
