# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-22 09:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0043_generalpromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('startDate', models.DateField(unique='true', verbose_name='Start Date')),
                ('endDate', models.DateField(verbose_name='End Date')),
                ('food_type', models.ManyToManyField(blank=True, null=True, to='ultimatefitbackend.FoodType')),
            ],
        ),
    ]
