# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0044_grouppromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPromotionFoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.FoodType')),
                ('group_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.GroupPromotion')),
            ],
        ),
    ]
