# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0045_grouppromotionfoodtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppromotion',
            name='startDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
