# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0046_auto_20180828_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppromotion',
            name='food_type',
        ),
        migrations.AlterUniqueTogether(
            name='grouppromotionfoodtypes',
            unique_together=set([('group_promotion', 'food_type')]),
        ),
    ]
