# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-30 12:44
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0048_couponpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponpromotion',
            name='available_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PERCENTAGE', 'Percentage (x%)'), ('PERCENTAGEWITHCAP', 'Percentage with cap (x%, capped at $y)'), ('ABSOLUTEWITHMIN', 'Absolute with min ($x, min $y)')], default='PERCENTAGE', max_length=1),
        ),
    ]
