# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0054_deliveryorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.Food'),
        ),
    ]
