# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0055_auto_20181021_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='food',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='order_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatefitbackend.FoodOrder'),
        ),
    ]
