# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0056_auto_20181021_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
