# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0058_deliveryorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
