# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0059_auto_20181021_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='order_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
