# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-27 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatefitbackend', '0060_auto_20181022_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='address_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
