# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-06 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ultimatefitbackend', '0062_addressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
